/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quick.start

class App {
    val greeting: String
        get() = "Hello world."
}

fun main(args: Array<String>) {
    println(App().greeting)
}
